-- Run after schema.sql to load the app's 21 sample rooms.
insert into public.rooms (id, name, building, floor, capacity, equipment, image_url, description, is_available_now)
values
('room-1', 'Lab Vi Mạch Bán Dẫn (K.A301)', 'KA', 3, 32, array['High-spec PC', 'Projector', 'AC', 'Whiteboard']::text[], 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&auto=format&fit=crop&q=80', 'Phòng Lab vi mạch bán dẫn trọng điểm của VKU được tài trợ từ dự án ODA Hàn Quốc (KOICA), trang bị bộ công cụ thiết kế vi mạch Synopsys và máy trạm chuyên dụng.', true),
('room-2', 'Smart Lab AI & IoT (V.A204)', 'VA', 2, 28, array['High-spec PC', 'Projector', 'AC']::text[], 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80', 'Phòng thực hành công nghệ thông minh tầng 2 Khu V.A, trang bị bộ kit thí nghiệm IoT, cảm biến công nghiệp, robot và hệ thống GPU server phục vụ huấn luyện AI.', true),
('room-3', 'VJIT Space — Sakura Room (K.A205)', 'KA', 2, 20, array['Projector', 'Whiteboard', 'AC']::text[], 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80', 'Không gian sáng tạo thuộc không gian VJIT Space tầng 2 Giảng đường K.A theo tiêu chuẩn Nhật Bản, phục vụ sinh viên viện CNTT Việt - Nhật học tập và giao lưu doanh nghiệp.', false),
('room-4', 'VJIT Space — Samurai Room (K.A206)', 'KA', 2, 15, array['Whiteboard', 'AC', 'Projector']::text[], 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&auto=format&fit=crop&q=80', 'Phòng học nhóm và thảo luận chuyên sâu phong cách Nhật Bản tại VJIT Space Khu K.A, trang bị bàn làm việc linh hoạt và bảng kính viết ý tưởng.', true),
('room-5', 'Phòng Máy Thực Hành K.A201', 'KA', 2, 40, array['High-spec PC', 'AC', 'Projector']::text[], 'https://images.unsplash.com/photo-1534452203293-494d7ddbf7e0?w=800&auto=format&fit=crop&q=80', 'Phòng máy thực hành lập trình ứng dụng di động, web và game tại Giảng đường K.A, cài sẵn môi trường React Native, Node.js, Android Studio và VS Code.', true),
('room-6', 'Phòng Máy Thực Hành K.A202', 'KA', 2, 40, array['High-spec PC', 'AC', 'Projector']::text[], 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80', 'Phòng máy tính cấu hình cao tầng 2 Khu K.A dành cho các môn học Cơ sở dữ liệu, Cấu trúc dữ liệu và Lập trình nâng cao.', false),
('room-7', 'VKU Innovation Hub (V.A101)', 'VA', 1, 50, array['High-spec PC', 'Projector', 'Whiteboard', 'AC']::text[], 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&auto=format&fit=crop&q=80', 'Trung tâm đổi mới sáng tạo và khởi nghiệp VKU tại tầng 1 Khu V.A (Maker Space & Co-working), nơi tổ chức Hackathon, Techshow và ươm tạo dự án sinh viên.', true),
('room-8', 'AltimaLab Nghiên Cứu Nhật Bản (K.B204)', 'KB', 2, 22, array['High-spec PC', 'Projector', 'AC', 'Whiteboard']::text[], 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&auto=format&fit=crop&q=80', 'Không gian hợp tác nghiên cứu và thực hành giữa VKU và Công ty ALTIMA (Nhật Bản) tại Khu K.B, phục vụ các dự án nhúng và vi điều khiển.', true),
('room-9', 'Phòng Lab Mạng Máy Tính & An Toàn TT (K.A305)', 'KA', 3, 30, array['High-spec PC', 'AC', 'Whiteboard']::text[], 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80', 'Phòng thí nghiệm hệ thống mạng Cisco CCNA và thực hành An toàn thông tin, phòng thủ mã độc và điều tra số.', true),
('room-10', 'Phòng Tự Học Nhóm Thư Viện (K.B101)', 'KB', 1, 12, array['AC', 'Whiteboard']::text[], 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&auto=format&fit=crop&q=80', 'Không gian tự học nhóm tại tầng 1 tòa nhà Thư viện VKU (Khu K.B), có wifi tốc độ cao, nguồn điện tại chỗ và môi trường học tập yên tĩnh.', true),
('room-11', 'Phòng Học Nhóm Cách Âm Thư Viện (K.B201)', 'KB', 2, 8, array['AC', 'Whiteboard']::text[], 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&auto=format&fit=crop&q=80', 'Phòng tự học trang bị kính cách âm tầng 2 Thư viện VKU, thích hợp cho việc thảo luận nhóm, làm việc đồ án tốt nghiệp không bị ảnh hưởng.', false),
('room-12', 'Phòng Lab Đa Phương Tiện & Hàn Ngữ (K.B301)', 'KB', 3, 35, array['High-spec PC', 'AC', 'Projector']::text[], 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&auto=format&fit=crop&q=80', 'Phòng thực hành đa phương tiện nghe nhìn hiện đại, phục vụ giảng dạy Tiếng Hàn, Tiếng Anh chuyên ngành CNTT và thiết kế đồ họa 2D/3D.', true),
('room-13', 'Phòng Hội Thảo Chuyên Đề K.C102', 'KC', 1, 35, array['Projector', 'Whiteboard', 'AC']::text[], 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop&q=80', 'Phòng hội thảo hiện đại tại tầng 1 Giảng đường K.C với máy chiếu siêu nét, hệ thống âm thanh giảng dạy và bàn ghế di động.', true),
('room-14', 'Phòng Seminar Khoa Học K.C201', 'KC', 2, 45, array['Projector', 'AC', 'Whiteboard']::text[], 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop&q=80', 'Phòng seminar học thuật tầng 2 Khu K.C, nơi diễn ra các buổi báo cáo nghiên cứu khoa học sinh viên và hội thảo chuyên môn.', false),
('room-15', 'Focus Pod K.C304 (Nghiên Cứu Độc Lập)', 'KC', 3, 4, array['AC', 'Whiteboard']::text[], 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&auto=format&fit=crop&q=80', 'Cabin học tập nhỏ gọn tại tầng 3 Giảng đường K.C dành cho nhóm nghiên cứu nhỏ 2-4 người ôn luyện đội tuyển ACM/ICPC.', true),
('room-16', 'VKU Fintech Hub & Kế Toán Ảo (V.A210)', 'VA', 2, 30, array['High-spec PC', 'AC', 'Projector']::text[], 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80', 'Phòng thực hành mô phỏng sàn giao dịch tài chính số, ngân hàng ảo và hệ thống phân tích định lượng công nghệ tài chính.', true),
('room-17', 'Phòng Lab Phần Mềm & AI NLT Group (K.A401)', 'KA', 4, 25, array['High-spec PC', 'Projector', 'AC']::text[], 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80', 'Phòng Lab hợp tác nghiên cứu công nghệ mới cùng Tập đoàn NLT tại tầng 4 Giảng đường K.A, phục vụ phát triển đô thị thông minh.', true),
('room-18', 'Mobile & Cloud Studio (V.A208)', 'VA', 2, 20, array['High-spec PC', 'AC', 'Whiteboard']::text[], 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&auto=format&fit=crop&q=80', 'Phòng thực hành công nghệ di động và điện toán đám mây tại Khu V.A, có dàn thiết bị test thực tế iPhone/iPad và Android phones.', false),
('room-19', 'Phòng Khóa Luận Tốt Nghiệp K.C204', 'KC', 2, 12, array['Whiteboard', 'AC', 'Projector']::text[], 'https://images.unsplash.com/photo-1497215842964-222b430dc094?w=800&auto=format&fit=crop&q=80', 'Không gian làm việc riêng biệt cho sinh viên K20, K21, K22, K23 trong giai đoạn hoàn thành đồ án tốt nghiệp kỹ sư/cử nhân.', true),
('room-20', 'Design Thinking & UI/UX Studio (V.A105)', 'VA', 1, 18, array['Projector', 'Whiteboard', 'AC']::text[], 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80', 'Studio tư duy thiết kế trải nghiệm người dùng tại tầng 1 Khu V.A, trang bị bảng tương tác, bảng vẽ điện tử và dụng cụ prototyping.', true),
('room-21', 'Phòng Họp Hội Đồng Đồ Án V.A401', 'VA', 4, 25, array['Projector', 'AC', 'Whiteboard']::text[], 'https://images.unsplash.com/photo-1431540015161-0bf868a2d407?w=800&auto=format&fit=crop&q=80', 'Phòng họp hội đồng tầng 4 Khu V.A dành cho các buổi bảo vệ đồ án chuyên ngành, phản biện luận văn và tiếp đón đoàn chuyên gia.', true)
on conflict (id) do update set
  name = excluded.name, building = excluded.building, floor = excluded.floor, capacity = excluded.capacity,
  equipment = excluded.equipment, image_url = excluded.image_url, description = excluded.description, is_available_now = excluded.is_available_now;
